(cl:defpackage study_pkg-msg
  (:use )
  (:export
   "<LEARNINGACTION>"
   "LEARNINGACTION"
   "<LEARNINGACTIONFEEDBACK>"
   "LEARNINGACTIONFEEDBACK"
   "<LEARNINGACTIONGOAL>"
   "LEARNINGACTIONGOAL"
   "<LEARNINGACTIONRESULT>"
   "LEARNINGACTIONRESULT"
   "<LEARNINGFEEDBACK>"
   "LEARNINGFEEDBACK"
   "<LEARNINGGOAL>"
   "LEARNINGGOAL"
   "<LEARNINGRESULT>"
   "LEARNINGRESULT"
   "<CONTROL>"
   "CONTROL"
  ))

