; Auto-generated. Do not edit!


(cl:in-package study_pkg-msg)


;//! \htmlinclude LearningGoal.msg.html

(cl:defclass <LearningGoal> (roslisp-msg-protocol:ros-message)
  ((target_accuracy
    :reader target_accuracy
    :initarg :target_accuracy
    :type cl:float
    :initform 0.0))
)

(cl:defclass LearningGoal (<LearningGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LearningGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LearningGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name study_pkg-msg:<LearningGoal> is deprecated: use study_pkg-msg:LearningGoal instead.")))

(cl:ensure-generic-function 'target_accuracy-val :lambda-list '(m))
(cl:defmethod target_accuracy-val ((m <LearningGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader study_pkg-msg:target_accuracy-val is deprecated.  Use study_pkg-msg:target_accuracy instead.")
  (target_accuracy m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LearningGoal>) ostream)
  "Serializes a message object of type '<LearningGoal>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'target_accuracy))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LearningGoal>) istream)
  "Deserializes a message object of type '<LearningGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'target_accuracy) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LearningGoal>)))
  "Returns string type for a message object of type '<LearningGoal>"
  "study_pkg/LearningGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LearningGoal)))
  "Returns string type for a message object of type 'LearningGoal"
  "study_pkg/LearningGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LearningGoal>)))
  "Returns md5sum for a message object of type '<LearningGoal>"
  "01862dc6d0b75f2ce1fc83b2e93b6318")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LearningGoal)))
  "Returns md5sum for a message object of type 'LearningGoal"
  "01862dc6d0b75f2ce1fc83b2e93b6318")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LearningGoal>)))
  "Returns full string definition for message of type '<LearningGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%float32 target_accuracy~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LearningGoal)))
  "Returns full string definition for message of type 'LearningGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%float32 target_accuracy~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LearningGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LearningGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'LearningGoal
    (cl:cons ':target_accuracy (target_accuracy msg))
))
