; Auto-generated. Do not edit!


(cl:in-package study_pkg-msg)


;//! \htmlinclude LearningFeedback.msg.html

(cl:defclass <LearningFeedback> (roslisp-msg-protocol:ros-message)
  ((current_accuracy
    :reader current_accuracy
    :initarg :current_accuracy
    :type cl:float
    :initform 0.0)
   (step_number
    :reader step_number
    :initarg :step_number
    :type cl:integer
    :initform 0))
)

(cl:defclass LearningFeedback (<LearningFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LearningFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LearningFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name study_pkg-msg:<LearningFeedback> is deprecated: use study_pkg-msg:LearningFeedback instead.")))

(cl:ensure-generic-function 'current_accuracy-val :lambda-list '(m))
(cl:defmethod current_accuracy-val ((m <LearningFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader study_pkg-msg:current_accuracy-val is deprecated.  Use study_pkg-msg:current_accuracy instead.")
  (current_accuracy m))

(cl:ensure-generic-function 'step_number-val :lambda-list '(m))
(cl:defmethod step_number-val ((m <LearningFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader study_pkg-msg:step_number-val is deprecated.  Use study_pkg-msg:step_number instead.")
  (step_number m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LearningFeedback>) ostream)
  "Serializes a message object of type '<LearningFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'current_accuracy))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'step_number)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'step_number)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'step_number)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'step_number)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LearningFeedback>) istream)
  "Deserializes a message object of type '<LearningFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'current_accuracy) (roslisp-utils:decode-single-float-bits bits)))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'step_number)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'step_number)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'step_number)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'step_number)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LearningFeedback>)))
  "Returns string type for a message object of type '<LearningFeedback>"
  "study_pkg/LearningFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LearningFeedback)))
  "Returns string type for a message object of type 'LearningFeedback"
  "study_pkg/LearningFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LearningFeedback>)))
  "Returns md5sum for a message object of type '<LearningFeedback>"
  "e351c2411951a69d81996b20bf44d2b1")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LearningFeedback)))
  "Returns md5sum for a message object of type 'LearningFeedback"
  "e351c2411951a69d81996b20bf44d2b1")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LearningFeedback>)))
  "Returns full string definition for message of type '<LearningFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%float32 current_accuracy~%uint32  step_number~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LearningFeedback)))
  "Returns full string definition for message of type 'LearningFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%float32 current_accuracy~%uint32  step_number~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LearningFeedback>))
  (cl:+ 0
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LearningFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'LearningFeedback
    (cl:cons ':current_accuracy (current_accuracy msg))
    (cl:cons ':step_number (step_number msg))
))
