; Auto-generated. Do not edit!


(cl:in-package study_pkg-msg)


;//! \htmlinclude LearningResult.msg.html

(cl:defclass <LearningResult> (roslisp-msg-protocol:ros-message)
  ((result_accuracy
    :reader result_accuracy
    :initarg :result_accuracy
    :type cl:float
    :initform 0.0)
   (step_count
    :reader step_count
    :initarg :step_count
    :type cl:integer
    :initform 0))
)

(cl:defclass LearningResult (<LearningResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LearningResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LearningResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name study_pkg-msg:<LearningResult> is deprecated: use study_pkg-msg:LearningResult instead.")))

(cl:ensure-generic-function 'result_accuracy-val :lambda-list '(m))
(cl:defmethod result_accuracy-val ((m <LearningResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader study_pkg-msg:result_accuracy-val is deprecated.  Use study_pkg-msg:result_accuracy instead.")
  (result_accuracy m))

(cl:ensure-generic-function 'step_count-val :lambda-list '(m))
(cl:defmethod step_count-val ((m <LearningResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader study_pkg-msg:step_count-val is deprecated.  Use study_pkg-msg:step_count instead.")
  (step_count m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LearningResult>) ostream)
  "Serializes a message object of type '<LearningResult>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'result_accuracy))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'step_count)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'step_count)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'step_count)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'step_count)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LearningResult>) istream)
  "Deserializes a message object of type '<LearningResult>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'result_accuracy) (roslisp-utils:decode-single-float-bits bits)))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'step_count)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'step_count)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'step_count)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'step_count)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LearningResult>)))
  "Returns string type for a message object of type '<LearningResult>"
  "study_pkg/LearningResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LearningResult)))
  "Returns string type for a message object of type 'LearningResult"
  "study_pkg/LearningResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LearningResult>)))
  "Returns md5sum for a message object of type '<LearningResult>"
  "f4aa625d75149fe3c3509c59d2af5c23")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LearningResult)))
  "Returns md5sum for a message object of type 'LearningResult"
  "f4aa625d75149fe3c3509c59d2af5c23")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LearningResult>)))
  "Returns full string definition for message of type '<LearningResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%float32 result_accuracy~%uint32  step_count~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LearningResult)))
  "Returns full string definition for message of type 'LearningResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%float32 result_accuracy~%uint32  step_count~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LearningResult>))
  (cl:+ 0
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LearningResult>))
  "Converts a ROS message object to a list"
  (cl:list 'LearningResult
    (cl:cons ':result_accuracy (result_accuracy msg))
    (cl:cons ':step_count (step_count msg))
))
