// Generated by gencpp from file study_pkg/Control.msg
// DO NOT EDIT!


#ifndef STUDY_PKG_MESSAGE_CONTROL_H
#define STUDY_PKG_MESSAGE_CONTROL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace study_pkg
{
template <class ContainerAllocator>
struct Control_
{
  typedef Control_<ContainerAllocator> Type;

  Control_()
    : x(0)
    , y(0)  {
    }
  Control_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)  {
  (void)_alloc;
    }



   typedef int64_t _x_type;
  _x_type x;

   typedef int64_t _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::study_pkg::Control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::study_pkg::Control_<ContainerAllocator> const> ConstPtr;

}; // struct Control_

typedef ::study_pkg::Control_<std::allocator<void> > Control;

typedef boost::shared_ptr< ::study_pkg::Control > ControlPtr;
typedef boost::shared_ptr< ::study_pkg::Control const> ControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::study_pkg::Control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::study_pkg::Control_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::study_pkg::Control_<ContainerAllocator1> & lhs, const ::study_pkg::Control_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::study_pkg::Control_<ContainerAllocator1> & lhs, const ::study_pkg::Control_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace study_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::study_pkg::Control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::study_pkg::Control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::study_pkg::Control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::study_pkg::Control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::study_pkg::Control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::study_pkg::Control_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::study_pkg::Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3b834ede922a0fff22c43585c533b49f";
  }

  static const char* value(const ::study_pkg::Control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3b834ede922a0fffULL;
  static const uint64_t static_value2 = 0x22c43585c533b49fULL;
};

template<class ContainerAllocator>
struct DataType< ::study_pkg::Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "study_pkg/Control";
  }

  static const char* value(const ::study_pkg::Control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::study_pkg::Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 x\n"
"int64 y\n"
;
  }

  static const char* value(const ::study_pkg::Control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::study_pkg::Control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::study_pkg::Control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::study_pkg::Control_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int64_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STUDY_PKG_MESSAGE_CONTROL_H
