// Generated by gencpp from file study_pkg/LearningResult.msg
// DO NOT EDIT!


#ifndef STUDY_PKG_MESSAGE_LEARNINGRESULT_H
#define STUDY_PKG_MESSAGE_LEARNINGRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace study_pkg
{
template <class ContainerAllocator>
struct LearningResult_
{
  typedef LearningResult_<ContainerAllocator> Type;

  LearningResult_()
    : result_accuracy(0.0)
    , step_count(0)  {
    }
  LearningResult_(const ContainerAllocator& _alloc)
    : result_accuracy(0.0)
    , step_count(0)  {
  (void)_alloc;
    }



   typedef float _result_accuracy_type;
  _result_accuracy_type result_accuracy;

   typedef uint32_t _step_count_type;
  _step_count_type step_count;





  typedef boost::shared_ptr< ::study_pkg::LearningResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::study_pkg::LearningResult_<ContainerAllocator> const> ConstPtr;

}; // struct LearningResult_

typedef ::study_pkg::LearningResult_<std::allocator<void> > LearningResult;

typedef boost::shared_ptr< ::study_pkg::LearningResult > LearningResultPtr;
typedef boost::shared_ptr< ::study_pkg::LearningResult const> LearningResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::study_pkg::LearningResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::study_pkg::LearningResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::study_pkg::LearningResult_<ContainerAllocator1> & lhs, const ::study_pkg::LearningResult_<ContainerAllocator2> & rhs)
{
  return lhs.result_accuracy == rhs.result_accuracy &&
    lhs.step_count == rhs.step_count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::study_pkg::LearningResult_<ContainerAllocator1> & lhs, const ::study_pkg::LearningResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace study_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::study_pkg::LearningResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::study_pkg::LearningResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::study_pkg::LearningResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::study_pkg::LearningResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::study_pkg::LearningResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::study_pkg::LearningResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::study_pkg::LearningResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f4aa625d75149fe3c3509c59d2af5c23";
  }

  static const char* value(const ::study_pkg::LearningResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf4aa625d75149fe3ULL;
  static const uint64_t static_value2 = 0xc3509c59d2af5c23ULL;
};

template<class ContainerAllocator>
struct DataType< ::study_pkg::LearningResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "study_pkg/LearningResult";
  }

  static const char* value(const ::study_pkg::LearningResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::study_pkg::LearningResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the result\n"
"float32 result_accuracy\n"
"uint32  step_count\n"
;
  }

  static const char* value(const ::study_pkg::LearningResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::study_pkg::LearningResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result_accuracy);
      stream.next(m.step_count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LearningResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::study_pkg::LearningResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::study_pkg::LearningResult_<ContainerAllocator>& v)
  {
    s << indent << "result_accuracy: ";
    Printer<float>::stream(s, indent + "  ", v.result_accuracy);
    s << indent << "step_count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.step_count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STUDY_PKG_MESSAGE_LEARNINGRESULT_H
