// Generated by gencpp from file study_pkg/PolyResponse.msg
// DO NOT EDIT!


#ifndef STUDY_PKG_MESSAGE_POLYRESPONSE_H
#define STUDY_PKG_MESSAGE_POLYRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace study_pkg
{
template <class ContainerAllocator>
struct PolyResponse_
{
  typedef PolyResponse_<ContainerAllocator> Type;

  PolyResponse_()
    : y(0)  {
    }
  PolyResponse_(const ContainerAllocator& _alloc)
    : y(0)  {
  (void)_alloc;
    }



   typedef int64_t _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::study_pkg::PolyResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::study_pkg::PolyResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PolyResponse_

typedef ::study_pkg::PolyResponse_<std::allocator<void> > PolyResponse;

typedef boost::shared_ptr< ::study_pkg::PolyResponse > PolyResponsePtr;
typedef boost::shared_ptr< ::study_pkg::PolyResponse const> PolyResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::study_pkg::PolyResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::study_pkg::PolyResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::study_pkg::PolyResponse_<ContainerAllocator1> & lhs, const ::study_pkg::PolyResponse_<ContainerAllocator2> & rhs)
{
  return lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::study_pkg::PolyResponse_<ContainerAllocator1> & lhs, const ::study_pkg::PolyResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace study_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::study_pkg::PolyResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::study_pkg::PolyResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::study_pkg::PolyResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::study_pkg::PolyResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::study_pkg::PolyResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::study_pkg::PolyResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::study_pkg::PolyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "448d6bc7e4d0fbf8c36fce045a54703f";
  }

  static const char* value(const ::study_pkg::PolyResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x448d6bc7e4d0fbf8ULL;
  static const uint64_t static_value2 = 0xc36fce045a54703fULL;
};

template<class ContainerAllocator>
struct DataType< ::study_pkg::PolyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "study_pkg/PolyResponse";
  }

  static const char* value(const ::study_pkg::PolyResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::study_pkg::PolyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 y\n"
"\n"
;
  }

  static const char* value(const ::study_pkg::PolyResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::study_pkg::PolyResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PolyResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::study_pkg::PolyResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::study_pkg::PolyResponse_<ContainerAllocator>& v)
  {
    s << indent << "y: ";
    Printer<int64_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STUDY_PKG_MESSAGE_POLYRESPONSE_H
