// Generated by gencpp from file study_pkg/Poly.msg
// DO NOT EDIT!


#ifndef STUDY_PKG_MESSAGE_POLY_H
#define STUDY_PKG_MESSAGE_POLY_H

#include <ros/service_traits.h>


#include <study_pkg/PolyRequest.h>
#include <study_pkg/PolyResponse.h>


namespace study_pkg
{

struct Poly
{

typedef PolyRequest Request;
typedef PolyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Poly
} // namespace study_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::study_pkg::Poly > {
  static const char* value()
  {
    return "7af389a0199f9d711ada5d5e7ae94cb3";
  }

  static const char* value(const ::study_pkg::Poly&) { return value(); }
};

template<>
struct DataType< ::study_pkg::Poly > {
  static const char* value()
  {
    return "study_pkg/Poly";
  }

  static const char* value(const ::study_pkg::Poly&) { return value(); }
};


// service_traits::MD5Sum< ::study_pkg::PolyRequest> should match
// service_traits::MD5Sum< ::study_pkg::Poly >
template<>
struct MD5Sum< ::study_pkg::PolyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::study_pkg::Poly >::value();
  }
  static const char* value(const ::study_pkg::PolyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::study_pkg::PolyRequest> should match
// service_traits::DataType< ::study_pkg::Poly >
template<>
struct DataType< ::study_pkg::PolyRequest>
{
  static const char* value()
  {
    return DataType< ::study_pkg::Poly >::value();
  }
  static const char* value(const ::study_pkg::PolyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::study_pkg::PolyResponse> should match
// service_traits::MD5Sum< ::study_pkg::Poly >
template<>
struct MD5Sum< ::study_pkg::PolyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::study_pkg::Poly >::value();
  }
  static const char* value(const ::study_pkg::PolyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::study_pkg::PolyResponse> should match
// service_traits::DataType< ::study_pkg::Poly >
template<>
struct DataType< ::study_pkg::PolyResponse>
{
  static const char* value()
  {
    return DataType< ::study_pkg::Poly >::value();
  }
  static const char* value(const ::study_pkg::PolyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STUDY_PKG_MESSAGE_POLY_H
