// Generated by gencpp from file study_pkg/PolyRequest.msg
// DO NOT EDIT!


#ifndef STUDY_PKG_MESSAGE_POLYREQUEST_H
#define STUDY_PKG_MESSAGE_POLYREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace study_pkg
{
template <class ContainerAllocator>
struct PolyRequest_
{
  typedef PolyRequest_<ContainerAllocator> Type;

  PolyRequest_()
    : x(0)  {
    }
  PolyRequest_(const ContainerAllocator& _alloc)
    : x(0)  {
  (void)_alloc;
    }



   typedef int64_t _x_type;
  _x_type x;





  typedef boost::shared_ptr< ::study_pkg::PolyRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::study_pkg::PolyRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PolyRequest_

typedef ::study_pkg::PolyRequest_<std::allocator<void> > PolyRequest;

typedef boost::shared_ptr< ::study_pkg::PolyRequest > PolyRequestPtr;
typedef boost::shared_ptr< ::study_pkg::PolyRequest const> PolyRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::study_pkg::PolyRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::study_pkg::PolyRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::study_pkg::PolyRequest_<ContainerAllocator1> & lhs, const ::study_pkg::PolyRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::study_pkg::PolyRequest_<ContainerAllocator1> & lhs, const ::study_pkg::PolyRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace study_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::study_pkg::PolyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::study_pkg::PolyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::study_pkg::PolyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::study_pkg::PolyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::study_pkg::PolyRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::study_pkg::PolyRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::study_pkg::PolyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b429044e1360891965aa67e074722c0e";
  }

  static const char* value(const ::study_pkg::PolyRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb429044e13608919ULL;
  static const uint64_t static_value2 = 0x65aa67e074722c0eULL;
};

template<class ContainerAllocator>
struct DataType< ::study_pkg::PolyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "study_pkg/PolyRequest";
  }

  static const char* value(const ::study_pkg::PolyRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::study_pkg::PolyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 x\n"
;
  }

  static const char* value(const ::study_pkg::PolyRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::study_pkg::PolyRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PolyRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::study_pkg::PolyRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::study_pkg::PolyRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.x);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STUDY_PKG_MESSAGE_POLYREQUEST_H
