// Auto-generated. Do not edit!

// (in-package study_pkg.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class LearningResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.result_accuracy = null;
      this.step_count = null;
    }
    else {
      if (initObj.hasOwnProperty('result_accuracy')) {
        this.result_accuracy = initObj.result_accuracy
      }
      else {
        this.result_accuracy = 0.0;
      }
      if (initObj.hasOwnProperty('step_count')) {
        this.step_count = initObj.step_count
      }
      else {
        this.step_count = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type LearningResult
    // Serialize message field [result_accuracy]
    bufferOffset = _serializer.float32(obj.result_accuracy, buffer, bufferOffset);
    // Serialize message field [step_count]
    bufferOffset = _serializer.uint32(obj.step_count, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type LearningResult
    let len;
    let data = new LearningResult(null);
    // Deserialize message field [result_accuracy]
    data.result_accuracy = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [step_count]
    data.step_count = _deserializer.uint32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'study_pkg/LearningResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'f4aa625d75149fe3c3509c59d2af5c23';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the result
    float32 result_accuracy
    uint32  step_count
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new LearningResult(null);
    if (msg.result_accuracy !== undefined) {
      resolved.result_accuracy = msg.result_accuracy;
    }
    else {
      resolved.result_accuracy = 0.0
    }

    if (msg.step_count !== undefined) {
      resolved.step_count = msg.step_count;
    }
    else {
      resolved.step_count = 0
    }

    return resolved;
    }
};

module.exports = LearningResult;
