// Auto-generated. Do not edit!

// (in-package study_pkg.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class LearningFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.current_accuracy = null;
      this.step_number = null;
    }
    else {
      if (initObj.hasOwnProperty('current_accuracy')) {
        this.current_accuracy = initObj.current_accuracy
      }
      else {
        this.current_accuracy = 0.0;
      }
      if (initObj.hasOwnProperty('step_number')) {
        this.step_number = initObj.step_number
      }
      else {
        this.step_number = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type LearningFeedback
    // Serialize message field [current_accuracy]
    bufferOffset = _serializer.float32(obj.current_accuracy, buffer, bufferOffset);
    // Serialize message field [step_number]
    bufferOffset = _serializer.uint32(obj.step_number, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type LearningFeedback
    let len;
    let data = new LearningFeedback(null);
    // Deserialize message field [current_accuracy]
    data.current_accuracy = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [step_number]
    data.step_number = _deserializer.uint32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'study_pkg/LearningFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'e351c2411951a69d81996b20bf44d2b1';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define a feedback message
    float32 current_accuracy
    uint32  step_number
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new LearningFeedback(null);
    if (msg.current_accuracy !== undefined) {
      resolved.current_accuracy = msg.current_accuracy;
    }
    else {
      resolved.current_accuracy = 0.0
    }

    if (msg.step_number !== undefined) {
      resolved.step_number = msg.step_number;
    }
    else {
      resolved.step_number = 0
    }

    return resolved;
    }
};

module.exports = LearningFeedback;
