// Auto-generated. Do not edit!

// (in-package study_pkg.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class LearningGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.target_accuracy = null;
    }
    else {
      if (initObj.hasOwnProperty('target_accuracy')) {
        this.target_accuracy = initObj.target_accuracy
      }
      else {
        this.target_accuracy = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type LearningGoal
    // Serialize message field [target_accuracy]
    bufferOffset = _serializer.float32(obj.target_accuracy, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type LearningGoal
    let len;
    let data = new LearningGoal(null);
    // Deserialize message field [target_accuracy]
    data.target_accuracy = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'study_pkg/LearningGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '01862dc6d0b75f2ce1fc83b2e93b6318';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the goal
    float32 target_accuracy
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new LearningGoal(null);
    if (msg.target_accuracy !== undefined) {
      resolved.target_accuracy = msg.target_accuracy;
    }
    else {
      resolved.target_accuracy = 0.0
    }

    return resolved;
    }
};

module.exports = LearningGoal;
